name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  prerequisites:
    uses: ./.github/workflows/test.yml

  pyodide:
    uses: ./.github/workflows/pyodide.yml

  documentation:
    needs: [prerequisites, pyodide]
    if: github.ref_name == 'main'
    uses: ./.github/workflows/docs.yml
    with:
      version: main
      alias: latest
